//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ProductLanguage() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.ProductLanguage", typeof(ProductLanguage).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Accepted products.
        /// </summary>
        public static string AcceptedProducts {
            get {
                return ResourceManager.GetString("AcceptedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Carbohydrates.
        /// </summary>
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Carbs.
        /// </summary>
        public static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Declined products.
        /// </summary>
        public static string DeclinedProducts {
            get {
                return ResourceManager.GetString("DeclinedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No pending products..
        /// </summary>
        public static string NoPendingProducts {
            get {
                return ResourceManager.GetString("NoPendingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pending products.
        /// </summary>
        public static string PendingProducts {
            get {
                return ResourceManager.GetString("PendingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Product manufacturer.
        /// </summary>
        public static string ProductManufacturer {
            get {
                return ResourceManager.GetString("ProductManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Protein.
        /// </summary>
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quantity Type.
        /// </summary>
        public static string QuantityType {
            get {
                return ResourceManager.GetString("QuantityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search Food.
        /// </summary>
        public static string SearchFood {
            get {
                return ResourceManager.GetString("SearchFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search product.
        /// </summary>
        public static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Snacks.
        /// </summary>
        public static string Snacks {
            get {
                return ResourceManager.GetString("Snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Supper.
        /// </summary>
        public static string Supper {
            get {
                return ResourceManager.GetString("Supper", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User products.
        /// </summary>
        public static string UserProducts {
            get {
                return ResourceManager.GetString("UserProducts", resourceCulture);
            }
        }
    }
}
