//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalTrainerApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalTrainerApi.Resources.EnumNames", typeof(EnumNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdzony.
        /// </summary>
        public static string ProductStateAccepted {
            get {
                return ResourceManager.GetString("ProductStateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzucony.
        /// </summary>
        public static string ProductStateDenied {
            get {
                return ResourceManager.GetString("ProductStateDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpatrywany.
        /// </summary>
        public static string ProductStatePending {
            get {
                return ResourceManager.GetString("ProductStatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prywatny.
        /// </summary>
        public static string ProductStatePrivate {
            get {
                return ResourceManager.GetString("ProductStatePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabiał.
        /// </summary>
        public static string ProductTypeDairyProducts {
            get {
                return ResourceManager.GetString("ProductTypeDairyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast food.
        /// </summary>
        public static string ProductTypeFastFood {
            get {
                return ResourceManager.GetString("ProductTypeFastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owoce.
        /// </summary>
        public static string ProductTypeFruits {
            get {
                return ResourceManager.GetString("ProductTypeFruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słodycze.
        /// </summary>
        public static string ProductTypeSweets {
            get {
                return ResourceManager.GetString("ProductTypeSweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warzywa.
        /// </summary>
        public static string ProductTypeVegetables {
            get {
                return ResourceManager.GetString("ProductTypeVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gramy.
        /// </summary>
        public static string QuantityTypeGrams {
            get {
                return ResourceManager.GetString("QuantityTypeGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mililitry.
        /// </summary>
        public static string QuantityTypeMilliliters {
            get {
                return ResourceManager.GetString("QuantityTypeMilliliters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paczka.
        /// </summary>
        public static string QuantityTypePackage {
            get {
                return ResourceManager.GetString("QuantityTypePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sztuka.
        /// </summary>
        public static string QuantityTypePiece {
            get {
                return ResourceManager.GetString("QuantityTypePiece", resourceCulture);
            }
        }
    }
}
